# Generated by Django 4.1.3 on 2022-12-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tag_answer_author_answer_iscorrect_answer_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
