# Generated by Django 4.1.3 on 2022-12-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_answer_title_alter_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='value',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/img/default-avatar-icon.jpg', null=True, upload_to=''),
        ),
    ]
