# Generated by Django 4.1.3 on 2022-12-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_like_value_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='value',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
