# Generated by Django 4.1.3 on 2022-12-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_like_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/img/default-avatar-icon.jpg', null=True, upload_to='static/img/avatar/%Y/%m/%d/'),
        ),
    ]
