# Generated by Django 4.1.3 on 2022-12-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/img/default-avatar-icon.jpg', null=True, upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
